//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Scripts/RubyInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @RubyInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @RubyInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""RubyInput"",
    ""maps"": [
        {
            ""name"": ""Ruby"",
            ""id"": ""dc4be964-cb17-48c1-86b9-fdc304ac3162"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""f52f8ab0-0829-455f-80e4-5705673de42f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""156d5c63-01a3-4d2d-b664-703fa9231dab"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Ruby
        m_Ruby = asset.FindActionMap("Ruby", throwIfNotFound: true);
        m_Ruby_Move = m_Ruby.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Ruby
    private readonly InputActionMap m_Ruby;
    private List<IRubyActions> m_RubyActionsCallbackInterfaces = new List<IRubyActions>();
    private readonly InputAction m_Ruby_Move;
    public struct RubyActions
    {
        private @RubyInput m_Wrapper;
        public RubyActions(@RubyInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Ruby_Move;
        public InputActionMap Get() { return m_Wrapper.m_Ruby; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RubyActions set) { return set.Get(); }
        public void AddCallbacks(IRubyActions instance)
        {
            if (instance == null || m_Wrapper.m_RubyActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RubyActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IRubyActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IRubyActions instance)
        {
            if (m_Wrapper.m_RubyActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRubyActions instance)
        {
            foreach (var item in m_Wrapper.m_RubyActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RubyActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RubyActions @Ruby => new RubyActions(this);
    public interface IRubyActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
}
